source/organization/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField, RadioField, DateField, BooleanField,SelectField
from wtforms import validators, ValidationError
from wtforms.fields.html5 import DateField

class AddOrg(FlaskForm):
	id = 'AddOrg'
	
	org_name =  TextField('Organization Name *', id='org_name' ) 
	org_type_of_entity = SelectField('Organization Type Of entity *', id='org_type_of_entity')
	org_nature_of_business = SelectField('Organization Nature Of Business', id='org_nature_of_business')
	org_company_registration_no = TextField('Organization Company Registration No', id='org_company_registration_no')	
	org_date_of_incorporation = DateField('Organization Date Of Incorporation',id='org_date_of_incorporation')


	org_address_line_1 =  TextField('Organization Address', id='org_address_line_1' )
	org_address_line_2 =  TextField('Organization Address 2', id='org_address_line_2' )
	org_city = TextField('Organization City',id='org_city') 
	org_state = TextField('Organization state',id='org_state')
	org_pin_code_no = TextField('Organization Pin Code No',id='org_pin_code_no')
	org_parmanent_account_number = TextField('Organization Permanent Account Number',id='org_parmanent_account_number')
	org_tax_deduction_account_number = TextField('Organization Tax Deduction Account Number',id='org_tax_deduction_account_number')
	org_goods_service_tax_registration_number = TextField('Organization Goods Service Tax Registration Number',id='org_goods_service_tax_registration_number')
	org_import_export_code = TextField('Organization Import Export Code',id='org_import_export_code')
	org_land_line_number = TextField('Organization Land Line Number',id='org_land_line_number')
	org_mobile_number = TextField('Organization Mobile Number',id='org_mobile_number')
	org_alternative_mobile_number = TextField('Organization Alternative Mobile Number',id='org_alternative_mobile_number')
	org_email_id = TextField('Organization Email Id *',[validators.Required("Please enter your email address."),validators.Email("Please enter your email address.")],id='org_email_id')
	org_alternative_email_id = TextField('Organization Alternative Email Id',[validators.Email("Please enter your email address.")],id='org_alternative_email_id')
	org_remarks = TextField('Organization Remarks',id='org_remarks') 
	submit = "submit"
		
class EditOrg(FlaskForm):
	id = 'EditOrg'
	
	org_name =  TextField('Organization Name', id='org_name' ) 
	org_type_of_entity = TextField('Organization Type Of entity', id='org_type_of_entity')
	org_nature_of_business = TextField('Organization Nature Of Business', id='org_nature_of_business')
	org_company_registration_no = TextField('Organization Company Registration No', id='org_company_registration_no')
	org_date_of_incorporation = DateField('Organization Date Of Incorporation', id='org_date_of_incorporation')
	org_address_line_1 =  TextField('Organization Address', id='org_address_line_1' )
	org_address_line_2 =  TextField('Organization Address 2', id='org_address_line_2' )
	org_city = TextField('Organization City',id='org_city') 
	org_state = TextField('Organization state',id='org_state')
	org_pin_code_no = TextField('Organization Pin Code No',id='org_pin_code_no')
	org_parmanent_account_number = TextField('Organization Permanent Account Number',id='org_parmanent_account_number')
	org_tax_deduction_account_number = TextField('Organization Tax Deduction Account Number',id='org_tax_deduction_account_number')
	org_goods_service_tax_registration_number = TextField('Organization Goods Service Tax Registration Number',id='org_goods_service_tax_registration_number')
	org_import_export_code = TextField('Organization Import Export Code',id='org_import_export_code')
	org_land_line_number = TextField('Organization Land Line Number',id='org_land_line_number')
	org_mobile_number = TextField('Organization Mobile Number',id='org_mobile_number')
	org_alternative_mobile_number = TextField('Organization Alternative Mobile Number',id='org_alternative_mobile_number')
	org_email_id = TextField('Organization Email Id *',[validators.Required("Please enter your email address."),validators.Email("Please enter your email address.")],id='org_email_id')
	org_alternative_email_id = TextField('Organization Alternative Email Id',[validators.Email("Please enter your email address.")],id='org_alternative_email_id')
	org_remarks = TextField('Organization Remarks',id='org_remarks')
	submit = "submit"

source/organization/routes.py
from flask import Blueprint, render_template, request
from flask_login import login_required, current_user
from flask import jsonify
import json


blueprint = Blueprint(
    'organization_blueprint',
    __name__,
    url_prefix='/organization',
    template_folder='templates',
    static_folder='static'
)


from database import db
from .forms import AddOrg
from .forms import EditOrg


from base.models import org_master,entity_type_master,business_type_master



@blueprint.route('/org', methods=['GET','POST'])
@login_required
def index():
    docList = db.session.query(entity_type_master.entity_type, entity_type_master.entity_type_id).all()
    docList2 = db.session.query(business_type_master.business_type, business_type_master.business_type_id).all()
    form = AddOrg(request.form)
    if 'submit' in request.form:        
        org = org_master(**request.form)
        print(org)
        db.session.add(org)
        db.session.commit()
    return render_template('addOrg.html', form = form, docList=docList, docList2=docList2)

@blueprint.route('/edit', methods=['GET','POST'])
@login_required
def index2():
    form = EditOrg(request.form)
    if 'submit' in request.form:
        org_name = str(request.form['org_name'])
        rw = db.session.query(org_master).filter_by(org_name=org_name).first()
        rw.org_address_line_1 = str(request.form['org_address_line_1'])
        db.session.commit()
    return render_template('EditOrg.html', form = form)

@blueprint.route('/_get_data/')
@login_required
def _get_data():
    #print("ABOUT TO GET THE DATA AND RETURNING THE JSON--------------")
    org_name = request.args.get('nm')
    #print(org_name)
    rowData = db.session.query(org_master).filter_by(org_name=org_name).first()
    print("~~~~~~~~~~~~~~~~~~")
    
    rowDict = rowData.__dict__ 
    rowDict.pop('_sa_instance_state', None)
    print(rowDict) 
    entityRow = db.session.query(entity_type_master).filter_by(entity_type_id=rowDict['org_type_of_entity']).first()
    print(entityRow)
    rowDict1 = entityRow.__dict__
    print(rowDict1) 
    rowDict['org_type_of_entity'] = rowDict1['entity_type']
    print("----------------")
    print(rowDict)
    print("----------------")
       
    return json.dumps(rowDict, default=str)
    

source/organization/templates/EditOrg.html
{% extends "base_site.html" %}

{% block title %} Organization {% endblock title %}

{% block stylesheets %}
  {{ super() }}
{% endblock stylesheets %}

{% block content %}


    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

    <!-- Include Date Range Picker -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
    <div class="right_col" role="main">
      <div class="">
       

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Edit Organization</h2>
                
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                  <br />


              <h2 style = "text-align: center;"></h2>
    
              {% for message in form.org_date_of_incorporation.errors %}
                 <div>{{ message }}</div>
              {% endfor %}
                
             
                <form id="demo-form" data-parsley-validate>


                
                

                <div class="form-group">

                  <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_name.label.text }} :</label>
                      <input type="text" id="{{ form.org_name.id }}" class="form-control" name="{{ form.org_name.id  }}" required />
                   </div>
                  

                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label class="control-label">{{ form.org_type_of_entity.label }}</label>
                      <input type="text" id="{{ form.org_type_of_entity.id }}" class="form-control" name="{{ form.org_type_of_entity.id }}" required />
                   </div>
                    <div class="col-md-1 col-sm-6 col-xs-12">
                      
                    </div>
                  </div>

                </div>

                <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12">
                      
                   
                    </div> 
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label class="control-label">{{ form.org_nature_of_business.label }}</label>
                      <input type="text" id="{{ form.org_nature_of_business.id }}" class="form-control" name="{{ form.org_nature_of_business.id }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_company_registration_no.label.text }} </label>
                      <input type="text" id="{{ form.org_company_registration_no.id }}" class="form-control" name="{{ form.org_company_registration_no.id }}" required />
                   </div>
                     <div class="col-md-1 col-sm-6 col-xs-12"></div>
                </div>
              </div>


              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_date_of_incorporation.label.text }} :</label>
                      <div class="row calendar-exibit">
                
                 

                  <fieldset>
                    <div class="control-group">
                      <div class="controls">
                        <div class="col-md-12 xdisplay_inputx form-group has-feedback">
                          <input type="text" class="form-control has-feedback-left" id="single_cal1" placeholder="First Name" aria-describedby="inputSuccess2Status">
                          <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                          <span id="inputSuccess2Status" class="sr-only">(success)</span>
                        </div>
                      </div>
                    
                  </fieldset>

                </div>
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_address_line_1.label.text }} </label>
                      <input type="text" id="{{ form.org_address_line_1.id }}" class="form-control" name="{{ form.org_address_line_1.id }}" required />
                   </div>
                  </div>
                </div>
                

              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_address_line_2.label.text }} :</label>
                      <input type="text" id="{{ form.org_address_line_2.id }}" class="form-control" name="{{ form.org_address_line_2.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_city.label.text }} </label>
                      <input type="text" id="{{ form.org_city.id }}" class="form-control" name="{{ form.org_city.id }}" required />
                   </div>
                </div>
              </div>


              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_state.label.text }} :</label>
                      <input type="text" id="{{ form.org_state.id }}" class="form-control" name="{{ form.org_state.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_pin_code_no.label.text }} </label>
                      <input type="text" data-inputmask="'mask' : '999-999'" id="{{ form.org_pin_code_no.id }}" class="form-control" name="{{ form.org_pin_code_no.id }}" required />
                   </div>
                </div>
              </div>

              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_parmanent_account_number.label.text }} :</label>
                      <input type="text" id="{{ form.org_parmanent_account_number.id }}" class="form-control" name="{{ form.org_parmanent_account_number.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_tax_deduction_account_number.label.text }} </label>
                      <input type="text" id="{{ form.org_tax_deduction_account_number.id }}" class="form-control" name="{{ form.org_tax_deduction_account_number.id }}" required />
                   </div>
                  </div>
                </div>
                

              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_goods_service_tax_registration_number.label.text }} :</label>
                      <input type="text" id="{{ form.org_goods_service_tax_registration_number.id }}" class="form-control" name="{{ form.org_goods_service_tax_registration_number.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_import_export_code.label.text }} </label>
                      <input type="text" id="{{ form.org_import_export_code.id }}" class="form-control" name="{{ form.org_import_export_code.id }}" required />
                   </div>
                </div>
              </div>

              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_land_line_number.label.text }} :</label>
                      <input type="text" id="{{ form.org_land_line_number.id }}" class="form-control" data-inputmask="'mask' : '(999) 999-9999'" name="{{ form.org_land_line_number.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_mobile_number.label.text }} </label>
                      <input type="text" id="{{ form.org_mobile_number.id }}" class="form-control" data-inputmask="'mask' : '(999) 999-9999'" name="{{ form.org_mobile_number.id }}" required />
                   </div>
                 </div> 
              </div> 

              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_alternative_mobile_number.label.text }} :</label>
                      <input type="text" id="{{ form.org_alternative_mobile_number.id }}" data-inputmask="'mask' : '(999) 999-9999'" class="form-control" name="{{ form.org_alternative_mobile_number.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_email_id.label.text }} </label>
                      <input type="email" id="{{ form.org_email_id.id }}" class="form-control" name="{{ form.org_email_id.id }}" required />
                   </div>
                 </div> 
              </div> 

              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_alternative_email_id.label.text }} :</label>
                      <input type="email" id="{{ form.org_alternative_email_id.id }}" class="form-control" name="{{ form.org_alternative_email_id.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_remarks.label.text }} </label>
                      <input type="text" id="{{ form.org_remarks.id }}" class="form-control" name="{{ form.org_remarks.id }}" required />
                   </div>
                 </div> 
              </div> 
              

              <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-4 col-sm-6 col-xs-12"></div>
                  <div class="col-md-8 col-sm-9 col-xs-12 ">
                    <button type="button" class="btn btn-primary">Cancel</button>
                   <button class="btn btn-primary" type="reset">Reset</button>
                    <button type="submit" class="btn btn-success" name="{{ form.submit }}">Submit</button>
                  </div>
                </div>

              </form>
              

             
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ super() }}

<script src="{{ url_for('static', filename='vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>
<script src="{{ url_for('static', filename='vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>


<script type="text/javascript">
    
    function updateData() 
    {
        
      org_name = $('#{{ form.org_name.id }}');
      var send = {nm : org_name.val()};

        $.getJSON("{{ url_for('organization_blueprint._get_data') }}", send, function(data) {
                    $.each(data, function(key,value) {
                    $('#' + key).val(value);
                  });
        });
    }

    $("#{{ form.org_name.id }}").change(function () {
      updateData(); 
  });    
  </script>
{% endblock javascripts %}