source/document/forms.py
from flask_wtf import FlaskForm
from wtforms import TextField, PasswordField, RadioField, SubmitField, SelectField,DateField,FileField

class Create(FlaskForm):
	id = 'createForm'
	docType = SelectField('Select Document Type', id='doc_type')
	submitBtnId = 'submit'

class Aadhar(FlaskForm):
	id = 'Aadhar'
	
	document_type_id =  TextField('Document Type Id', id='document_type_id' ) 
	document_type = TextField('Document Type', id='document_type')
	document_id = TextField('Document Id', id='document_id')
	org_id = TextField('Organization Id', id='org_id')
	user_id = TextField('User Id', id='user_id')
	dt_aadhar_num =  TextField('Aadhar card Number', id='dt_aadhar_num' )
	dt_aadhar_name =  TextField('Aadhar Name', id='dt_aadhar_name' )
	dt_aadhar_parent_or_spouse_name = TextField('Father or Spouse Name',id='dt_aadhar_parent_or_spouse_name') 
	dt_aadhar_dob = DateField('Date Of Birth',id='dt_aadhar_dob')
	dt_aadhar_gender = RadioField('Gender', choices = [('Male','Male'),('Female','Female')],id='dt_aadhar_gender')
	dt_aadhar_address1 = TextField('Address Line-1',id='dt_aadhar_address1')
	dt_aadhar_address2 = TextField('Address Line-2',id='dt_aadhar_address2')
	dt_aadhar_city = TextField('City',id='dt_aadhar_city')
	dt_aadhar_state = TextField('State',id='dt_aadhar_state')
	dt_aadhar_pin = TextField('Pin Code Number',id='dt_aadhar_pin')
	dt_aadhar_filepathandname = FileField('Upload PDF file',id='dt_aadhar_filepathandname')
	dt_aadhar_remarks = TextField('Remark',id='dt_aadhar_remarks')
	submit="submit"


class PanCard(FlaskForm):
	id = 'PanCard'
	
	document_type_id =  TextField('Document Type Id', id='document_type_id' ) 
	document_type = TextField('Document Type', id='document_type')
	document_id = TextField('Document Id', id='document_id')
	org_id = TextField('Organization Id', id='org_id')
	user_id = TextField('User Id', id='user_id')
	dt_pancard_pannum =  TextField('Pan card Number', id='dt_pancard_pannum' )
	dt_pancard_panname =  TextField('Pan Name', id='dt_pancard_panname' )
	dt_pancard_panfathersname = TextField('Fathers Name',id='dt_pancard_panfathersname') 
	dt_pancard_dob = DateField('Date Of Birth',id='dt_pancard_dob')
	dt_pancard_wardnum = TextField('Ward Number',id='dt_pancard_wardnum')
	dt_pancard_filepathandname = FileField('Upload PDF file ',id='dt_pancard_filepathandname')
	dt_pancard_remarks = TextField('Remarks',id='dt_pancard_remarks')
	submit="submit"
	

source/document/routes.py
from flask import Blueprint, render_template, request
from flask_login import login_required
from flask import jsonify
import json


from database import db
from .forms import Create,PanCard,Aadhar
from base.models import document_type_master
from base.models import dt_pancard,dt_aadhar


blueprint = Blueprint(
    'document_blueprint',
    __name__,
    url_prefix='/document',
    template_folder='templates',
    static_folder='static'
)



@blueprint.route('/document', methods=['GET','POST'])
@login_required
def index():
	docList = db.session.query(document_type_master.document_type, document_type_master.document_type_id).all()
	print(docList)
	form = Create(request.form)
	return render_template('document.html', form=form, docList = docList)


@blueprint.route('/panCard', methods=['GET','POST'])
@login_required
def index2():
	form = PanCard(request.form)
	if 'submit' in request.form:
		card_id = str(request.form['document_id'])
		
		rw = db.session.query(dt_pancard).filter_by(document_id=card_id).first()
		rw.dt_pancard_panname = str(request.form['dt_pancard_panname'])
		db.session.commit()
	return render_template('panCard.html', form = form)


@blueprint.route('/_get_data/')
@login_required
def _get_data():
    
    document_id = request.args.get('nm')
    
    rowData = db.session.query(dt_pancard).filter_by(document_id=document_id).first()
    print (rowData.user_id)
    print ("------------")
    rowDict = rowData.__dict__ 
    rowDict.pop('_sa_instance_state', None)
    return json.dumps(rowDict, default=str)
    


@blueprint.route('/aadharCard', methods=['GET','POST'])
@login_required
def index3():
	form = Aadhar(request.form)
	if 'submit' in request.form:
		card_id = str(request.form['document_id'])
		rw = db.session.query(dt_aadhar).filter_by(document_id=card_id).first()
		rw.dt_aadhar_name = str(request.form['dt_aadhar_name'])
		db.session.commit()
	return render_template('aadharCard.html', form = form)

@blueprint.route('/_get_dataA/')
@login_required
def _get_dataA():
    
    document_id = request.args.get('nm')
    
    rowData = db.session.query(dt_aadhar).filter_by(document_id=document_id).first()
    print (rowData)
    rowDict = rowData.__dict__ 
    
    rowDict.pop('_sa_instance_state', None)
    return json.dumps(rowDict, default=str)

source/document/templates/aadharCard.html
{% extends "base_site.html" %}

{% block title %} Aadhar Card {% endblock title %}

{% block stylesheets %}
  {{ super() }}
{% endblock stylesheets %}

{% block content %}


    <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

   
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>
    <div class="right_col" role="main">
      <div class="">
       

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Aadhar Card</h2>
                
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
                  <br />


              <h2 style = "text-align: center;"></h2>
    
              <form id="demo-form" data-parsley-validate>


                
                

              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.document_type_id.label.text }} :</label>
                      <input type="text" id="{{ form.document_type_id.id }}" class="form-control" name="{{ form.document_type_id.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.document_type.label.text }} </label>
                      <input type="text" id="{{ form.document_type.id }}" class="form-control" name="{{ form.document_type.id }}" required />
                   </div>

                </div>
              </div>

                <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.document_id.label.text }} :</label>
                      <input type="text" id="{{ form.document_id.id }}" class="form-control" name="{{ form.document_id.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.org_id.label.text }} </label>
                      <input type="text" id="{{ form.org_id.id }}" class="form-control" name="{{ form.org_id.id }}" required />
                   </div>

                </div>
              </div>



              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.user_id.label.text }} :</label>
                      <input type="text" id="{{ form.user_id.id }}" class="form-control" name="{{ form.user_id.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_num.label.text }} </label>
                      <input type="text" id="{{ form.dt_aadhar_num.id }}" class="form-control" name="{{ form.dt_aadhar_num.id }}" required />
                   </div>

                </div>
              </div>

              


              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_name.label.text }} :</label>
                      <input type="text" id="{{ form.dt_aadhar_name.id }}" class="form-control" name="{{ form.dt_aadhar_name.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_parent_or_spouse_name.label.text }} </label>
                      <input type="text" id="{{ form.dt_aadhar_parent_or_spouse_name.id }}" class="form-control" name="{{ form.dt_aadhar_parent_or_spouse_name.id }}" required />
                   </div>

                </div>
              </div>

              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_dob.label.text }} :</label>
                      <div class="row calendar-exibit">
                
                 

                  <fieldset>
                    <div class="control-group">
                      <div class="controls">
                        <div class="col-md-12 xdisplay_inputx form-group has-feedback">
                          <input type="text" class="form-control has-feedback-left" id="single_cal1" placeholder="First Name" aria-describedby="inputSuccess2Status">
                          <span class="fa fa-calendar-o form-control-feedback left" aria-hidden="true"></span>
                          <span id="inputSuccess2Status" class="sr-only">(success)</span>
                        </div>
                      </div>
                    
                  </fieldset>

                    </div>
                  </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                       <label class="control-label ">{{ form.dt_aadhar_gender.label }}</label><br>
                  
            <!--
                  <input type="radio" class="flat" name="user_gender" value="{{ Male }}" id="Male">
                  <label for="{{Male}}"> Male </label><br>
                  <input type="radio" class="flat" name="user_gender" value="{{ Female }}" id="Female">
                  <label for="{{Female}}"> Female </label><br>-->
                  {% for subfield in form.dt_aadhar_gender %}
                      <tr>
                          <td>{{ subfield }}</td>
                          <td>{{ subfield.label }}</td>
                      </tr><br>
                      {% endfor %}
                  
                </div>

                   </div>

                </div>
              </div>


              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_address1.label.text }} :</label>
                      <input type="text" id="{{ form.dt_aadhar_address1.id }}" class="form-control" name="{{ form.dt_aadhar_address1.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_address2.label.text }} </label>
                      <input type="text" id="{{ form.dt_aadhar_address2.id }}" class="form-control" name="{{ form.dt_aadhar_address2.id }}" required />
                   </div>

                </div>
              </div>

              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_city.label.text }} :</label>
                      <input type="text" id="{{ form.dt_aadhar_city.id }}" class="form-control" name="{{ form.dt_aadhar_city.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_state.label.text }} </label>
                      <input type="text" id="{{ form.dt_aadhar_state.id }}" class="form-control" name="{{ form.dt_aadhar_state.id }}" required />
                   </div>

                </div>
              </div>


              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_pin.label.text }} :</label>
                      <input type="text" data-inputmask="'mask' : '999-999'" id="{{ form.dt_aadhar_pin.id }}" class="form-control" name="{{ form.dt_aadhar_pin.id  }}" required />
                   </div>
                  
                  <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_filepathandname.label.text }} </label>
                      <input type="text" id="{{ form.dt_aadhar_filepathandname.id }}" class="form-control" name="{{ form.dt_aadhar_filepathandname.id }}" required />
                   </div>

                </div>
              </div>


              <div class="form-group">
                <div class="row">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>  
                   <div class="col-md-5 col-sm-6 col-xs-12">
                      <label for="">{{ form.dt_aadhar_remarks.label.text }} :</label>
                      <input type="text" id="{{ form.dt_aadhar_remarks.id }}" class="form-control" name="{{ form.dt_aadhar_remarks.id  }}" required />
                   </div>
                  
                  

                </div>
              </div>


              <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-4 col-sm-6 col-xs-12"></div>
                  <div class="col-md-8 col-sm-9 col-xs-12 ">
                    <button type="button" class="btn btn-primary">Cancel</button>
                   <button class="btn btn-primary" type="reset">Reset</button>
                    <button type="submit" class="btn btn-success" name="{{ form.submit }}">Submit</button>
                  </div>
                </div>

              </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ super() }}

<script src="{{ url_for('static', filename='vendors/jquery.inputmask/dist/min/jquery.inputmask.bundle.min.js') }}"></script>

<script type="text/javascript">
    
    function updateData() 
    {
        
      document_id = $('#{{ form.document_id.id }}');
      var send = {nm : document_id.val()};

        $.getJSON("{{ url_for('document_blueprint._get_dataA') }}", send, function(data) {
                    $.each(data, function(key,value) {
                      alert(key + " : " + value);
                    $('#' + key).val(value);
                  });
        });
    }

    $("#{{ form.document_id.id }}").change(function () {
      updateData(); 
  });    
  </script>




{% endblock javascripts %}

source/document/templates/document.html
2 {% extends "base_site.html" %}

{% block title %} Document {% endblock title %}

{% block stylesheets %}
  {{ super() }}
{% endblock stylesheets %}

{% block content %}
    <div class="right_col" role="main">
      <div class="">
        

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Documents</h2>
                
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
              
                  <form id="{{ form.id }}" data-parsley-validate class="form-horizontal form-label-left" method="post">
                  <div class="form-group">
                    <label class="control-label col-md-3 col-sm-3 col-xs-12">{{ form.docType.label }}</label>
                    <div class="col-md-6 col-sm-6 col-xs-12">
                      <select class="select2_single form-control" tabindex="-1">
                        <option></option>
                        {% for itm in docList %}
                          <option value={{ itm[1] }}>{{ itm[0] }}</option>
                        {%  endfor %}
                      </select>
                    </div>
                  </div>
              	</form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ super() }}
{% endblock javascripts %}

source/document/templates/panCard.html
2 {% extends "base_site.html" %}

{% block title %} Pan card {% endblock title %}

{% block stylesheets %}
  {{ super() }}
{% endblock stylesheets %}

{% block content %}

     <script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>

    <!-- Include Date Range Picker -->
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/js/bootstrap-datepicker.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.css"/>

    <div class="right_col" role="main">
      <div class="">
        

        <div class="clearfix"></div>

        <div class="row">
          <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
              <div class="x_title">
                <h2>Pan Card Documents</h2>
                
                <div class="clearfix"></div>
              </div>
              <div class="x_content">
              
                  <form class="form-horizontal form-label-left input_mask" id="{{ form.id }}" method="post">
                
                
                
                <div class="form-group">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>
                  <div class="col-md-5 col-sm-6 col-xs-12 form-group has-feedback">
                    <label class="control-label">{{ form.document_type_id.label }}</label>
                    <input type="text" class="form-control " required="required"  id="{{ form.document_type_id.id }}" name="{{ form.document_type_id.id }}" title="{{ form.document_type_id.label.text }}">
                  </div>
                 
                  <div class="col-md-5 col-sm-6 col-xs-12 form-group has-feedback">
                    <label class="control-label ">{{ form.document_type.label }}</label> 
                    <input type="text" class="form-control " required="required"  id="{{ form.document_type.id }}" name="{{ form.document_type.id }}">
                  </div>

                </div>

                <div class="form-group">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>                  
                  <div class="col-md-5 col-sm-6 col-xs-12 form-group has-feedback">
                    <label class="control-label ">{{ form.document_id.label }}</label> 
                    <input type="text" class="form-control " required="required"  id="{{ form.document_id.id }}" name="{{ form.document_id.id }}">
                  </div>

                  <div class="col-md-5 col-sm-6 col-xs-12">
                    <label class="control-label ">{{ form.org_id.label }}</label> 
                    <input type="text" class="form-control "   id="{{ form.org_id.id }}" name="{{ form.org_id.id }}">
                  </div>
                </div>

            
                <div class="form-group">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>
                  <div class="col-md-5 col-sm-6 col-xs-12 form-group has-feedback">
                    <label class="control-label ">{{ form.user_id.label }} </label> 
                    <input type="text" class="form-control " id="{{ form.user_id.id }}" name="{{ form.user_id.id }}">
                  </div>
               
               <div class="col-md-5 col-sm-1 col-xs-12">
                  <label class="control-label ">{{ form.dt_pancard_pannum.label }}</label> 
                    <input type="text" class="form-control " required="required"  id= "{{ form.dt_pancard_pannum.id }}" name="{{ form.dt_pancard_pannum.id }}">
                  </div>
                </div>




                <div class="form-group">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>
                  <div class="col-md-5 col-sm-6 col-xs-12 ">
                    <label class="control-label ">{{ form.dt_pancard_panname.label }}</label> 
                    <input type="text" class="form-control "  id= "{{ form.dt_pancard_panname.id }}" name="{{ form.dt_pancard_panname.id }}">
                  </div>
                  <div class="col-md-5 col-sm-6 col-xs-12">
                   <label class="control-label ">{{ form.dt_pancard_panfathersname.label }}</label> 
                    <input type="text" class="form-control "  id= "{{ form.dt_pancard_panfathersname.id }}" name="{{ form.dt_pancard_panfathersname.id }}">
                  </div>
                </div>

                <div class="form-group">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>
                  <div class="col-md-5 col-sm-6 col-xs-12 form-group has-feedback">
                    <label class="control-label ">{{ form.dt_pancard_dob.label }}</label> 
                    <div class="input-append date" id="{{ form.dt_pancard_dob.id }}" data-date-format="yyyy-mm-dd">
                    <input type="text" class="form-control "  id= "{{ form.dt_pancard_dob.id }}" name="{{ form.dt_pancard_dob.id }}">
                        <span class="add-on"><i class="icon-th"></i></span>
                      </div>
                  </div>              
               <script type="text/javascript">
                
               $('#{{ form.dt_pancard_dob.id }}').datepicker({
                  format: 'yyyy-mm-dd'
               });
               </script>
                  <div class="col-md-5 col-sm-6 col-xs-12 form-group has-feedback">
                   <label class="control-label ">{{ form.dt_pancard_wardnum.label }}</label> 
                    <input type="text" class="form-control "   id= "{{ form.dt_pancard_wardnum.id }}" name="{{ form.dt_pancard_wardnum.id }}">
                  </div>
                </div>


              <div class="form-group">
                  <div class="col-md-1 col-sm-6 col-xs-12"></div>
                  <div class="col-md-5 col-sm-6 col-xs-12 form-group has-feedback">
                   <label class="control-label ">{{ form.dt_pancard_filepathandname.label }}</label>  
                    <input type="text" class="form-control "  id= "{{ form.dt_pancard_filepathandname.id }}" name="{{ form.dt_pancard_filepathandname.id }}">
                  </div>
                  <div class="col-md-5 col-sm-6 col-xs-12">
                    <label class="control-label ">{{ form.dt_pancard_remarks.label }}</label> 
                    <input type="text" class="form-control "  id= "{{ form.dt_pancard_remarks.id }}" name="{{ form.dt_pancard_remarks.id }}">
                  </div>
                </div>

                
                
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-4 col-sm-6 col-xs-12"></div>
                  <div class="col-md-8 col-sm-9 col-xs-12 ">
                    <button type="button" class="btn btn-primary">Cancel</button>
         <button class="btn btn-primary" type="reset">Reset</button>
                    <button type="submit" class="btn btn-success" name="{{ form.submit }}">Submit</button>
                  </div>
                </div>

              </form>
              
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock content %}

{% block javascripts %}
  {{ super() }}

<script type="text/javascript">
    
    function updateData() 
    {
        
      document_id = $('#{{ form.document_id.id }}');
      var send = {nm : document_id.val()};

        $.getJSON("{{ url_for('document_blueprint._get_data') }}", send, function(data) {
                    $.each(data, function(key,value) {
                        alert(key + " : " + value);
                    $('#' + key).val(value);
                  
                  });
        });
    }

    $("#{{ form.document_id.id }}").change(function () {
      updateData(); 
  });    
  </script>

{% endblock javascripts %}